# github action for deploying Laravel APP to production via FTP
name: Deploy Site on push
on:
  push:
    branches:
      - master

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get the latest code
        uses: actions/checkout@v2.3.2
        with:
          fetch-depth: 2
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install Dependencies
        run: composer update --ignore-platform-reqs
      - name: Generate key
        run: php artisan key:generate
      - name: Sync files
        run: git config git-ftp.url ${{ secrets.LARAVEL_SITE_SERVER }}
      - run: git config git-ftp.user ${{ secrets.LARAVEL_SITE_USERNAME }}
      - run: git config git-ftp.password ${{ secrets.LARAVEL_SITE_PASSWORD }}
      - run: git config --global user.email "you@example.com"
      - run: git config --global user.name "Your Name"
      - run: git status
      - run: git add .
      - run: git commit -m "aa"
      - run: git status
      - run: git ftp catchup
      - run: git ftp push
