# Openstack Heat create instance with network resources
heat_template_version: 2016-10-14

description: Simple template to deploy a single compute instance 
resources:
  heat-network-1:
    type: OS::Neutron::Net
    properties:
      name: heat-network-1

  heat-subnet-1:
    type: OS::Neutron::Subnet
    properties:
      name: heat-subnet-1
      network: { get_resource: heat-network-1 }
      cidr: "172.28.1.0/24"
      allocation_pools: [{"start": "172.28.1.10", "end": "172.28.1.254"}]
      dns_nameservers: [ "8.8.8.8", "8.8.4.4" ]
      gateway_ip: "172.28.1.1"
      enable_dhcp: true
      ip_version: 4

  heat-router-1:
    type: OS::Neutron::Router
    properties:
      external_gateway_info: { network: external-net-1 }
    
  heat-router-1-interace:
    type: OS::Neutron::RouterInterface
    properties:
      router_id: { get_resource: heat-router-1 }
      subnet: { get_resource: heat-subnet-1 }

  heat-server-port:
    type: OS::Neutron::Port
    properties:
      network: { get_resource: heat-network-1 }
      security_groups:
        - default
        - { get_resource: heat-sg-1 }
      fixed_ips:
        - subnet_id: { get_resource: heat-subnet-1 }

  heat-sg-1:
    type: OS::Neutron::SecurityGroup
    properties:
      name: heat-sg-1
      rules:
        - protocol: tcp
          direction: ingress
          port_range_min: 22
          port_range_max: 22
        - protocol: icmp

  heat-key-1:
    type: OS::Nova::KeyPair
    properties:
      public_key: '[public key]'
      name: heat-key-1

  heat-flavor-1:
    type: OS::Nova::Flavor
    properties:
      name: heat-flavor-1
      vcpus: 2
      ram: 512
      disk: 10
      
  heat-instance-1: 
    type: OS::Nova::Server 
    properties: 
      image: cirros-1
      key_name: { get_resource: heat-key-1 }
      networks:
        - port: { get_resource: heat-server-port }
      flavor: { get_resource: heat-flavor-1}
      name: heat-instance-1

  heat-server-floating-ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: "external-net-1"

  heat-server-ip-assoc:
    type: OS::Neutron::FloatingIPAssociation
    properties:
      floatingip_id: { get_resource: heat-server-floating-ip }
      port_id: { get_resource: heat-server-port }

#outputs:
#  private_key:
#    description: Private key
#    value: { get_attr: [ heat-key-1, public_key ] }
